heat_template_version: 2013-05-23

description: Template to deploy devstack environment.

parameter_groups:

- label: Private Network Settings
  parameters:
  - private_network_cidr
  - private_network_label

- label: Server Settings
  parameters:
  - image

- label: Database Settings
  parameters:
  - database_server_hostname
  - database_server_flavor

# - label: Webserver Settings
#   parameter:
#   - web_server_hostname
#   - web_server_flavor

parameters:

  private_network_cidr:
    label: Private Network CIDR
    description: The CIDR for your Private Network
    type: string
    default: 192.168.42.0/24

  private_network_label:
    label: Private Network Label
    description: The name of your Private Network
    type: string
    default: DevNet
    constraints:
    - length:
        min: 3
        max: 64

  database_server_hostname:
    label: Server Name
    description: Hostname to use for your Database Server
    type: string
    default: data
    constraints:
    - length:
        min: 1
        max: 64
    - allowed_pattern: "^[a-zA-Z][a-zA-Z0-9-]*$"
      description: |
        Must begin with a letter and contain only alphanumeric characters.

  # web_server_hostname:
  #   label: Server Name
  #   description: Hostname to use for your Web Server
  #   type: string
  #   default: web
  #   constraints:
  #   - length:
  #       min: 1
  #       max: 64
  #   - allowed_pattern: "^[a-zA-Z][a-zA-Z0-9-]*$"
  #     description: |
  #       Must begin with a letter and contain only alphanumeric characters.

  image:
    label: Operating System
    description: |
      Server image used for all servers that are created as a part of this
      deployment
    type: string
    default: Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
    # default: Ubuntu 12.04 LTS (Precise Pangolin)
    constraints:
    - allowed_values:
      # - Ubuntu 12.04 LTS (Precise Pangolin)
      - Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
      description: Must be a supported operating system.

  database_server_flavor:
    label: Server Size
    description: |
      Cloud Server size to use for the database server. Sizes refer to the
      amount of RAM allocated to the server.
    type: string
    default: 1 GB Performance
    constraints:
    - allowed_values:
      - 1 GB Performance
      - 2 GB Performance
      - 4 GB Performance
      - 8 GB Performance
      - 15 GB Performance
      - 30 GB Performance
      - 1GB Standard Instance
      - 2GB Standard Instance
      - 4GB Standard Instance
      - 8GB Standard Instance
      - 15GB Standard Instance
      - 30GB Standard Instance
      description: |
        Must be a valid Rackspace Cloud Server flavor for the region you have
        selected to deploy into.

  # web_server_flavor:
  #   label: Server Size
  #   description: |
  #     Cloud Server size to use for the web server. Sizes refer to the
  #     amount of RAM allocated to the server.
  #   type: string
  #   default: 2 GB Performance
  #   constraints:
  #   - allowed_values:
  #     - 1 GB Performance
  #     - 2 GB Performance
  #     - 4 GB Performance
  #     - 8 GB Performance
  #     - 15 GB Performance
  #     - 30 GB Performance
  #     - 2GB Standard Instance
  #     - 4GB Standard Instance
  #     - 8GB Standard Instance
  #     - 15GB Standard Instance
  #     - 30GB Standard Instance
  #     description: |
  #       Must be a valid Rackspace Cloud Server flavor for the region you have
  #       selected to deploy into.

  # Chef parameters
  kitchen:
    description: |
      URL for the kitchen to clone with git.
    type: string
    default: https://github.com/dboune/devstack

  chef_version:
    description: Version of chef client to use
    type: string
    default: 11.12.8-2
    #default: 11.12.4

resources:

  # Random password generation
  mysql_root_password:
    type: "OS::Heat::RandomString"
    properties:
      length: 32
      sequence: lettersdigits

  mysql_repl_password:
    type: "OS::Heat::RandomString"
    properties:
      length: 32
      sequence: lettersdigits

  mysql_debian_password:
    type: "OS::Heat::RandomString"
    properties:
      length: 32
      sequence: lettersdigits

  # SSH keys
  ssh_key:
    type: "OS::Nova::KeyPair"
    properties:
      name: { get_param: "OS::stack_id" }
      save_private_key: true

  # Private Network
  private_network:
    type: "Rackspace::Cloud::Network"
    properties:
      cidr: { get_param: private_network_cidr }
      label: { get_parm: private_network_label }

  # Servers
  database_server:
    type: "Rackspace::Cloud::Server"
    depends_on: private_network
    properties:
      name: { get_param: database_server_hostname }
      flavor: { get_param: database_server_flavor }
      image: { get_param: image }
      key_name: { get_resource: ssh_key }
      networks:
      - uuid: "00000000-0000-0000-0000-000000000000"
      - uuid: "11111111-1111-1111-1111-111111111111"
      - uuid: { get_resource: private_network }

  # web_server:
  #   type: "Rackspace::Cloud::Server"
  #   depends_on: private_network
  #   properties:
  #     name: { get_param: web_server_hostname }
  #     flavor: { get_param: web_server_flavor }
  #     image: { get_param: image }
  #     key_name: { get_resource: ssh_key }
  #     networks: [ { "network": "PublicNet" }, { "network": "ServiceNet" }, {"network": get_attr: [private_network, label]} ]

  # Server Configurations
  database_server_setup:
    type: "OS::Heat::ChefSolo"
    depends_on: database_server
    properties:
      username: root
      private_key: { get_attr: [ssh_key, private_key] }
      host: { get_attr: [database_server, accessIPv4] }
      kitchen: { get_param: kitchen }
      chef_version: { get_param: chef_version }
      node:
        hollandbackup:
          main:
            backup_directory: "/var/lib/mysqlbackup"
            mysqldump:
              user: "root"
              host: "localhost"
              password: { get_attr: [mysql_root_password, value] }
        memcached:
          memory: 256
          # listen: { get_attr: [database_server, privateIPv4] }
        mysql:
          # bind_address: { get_attr: [database_server, privateIPv4] }
          server_root_password: { get_attr: [mysql_root_password, value] }
          server_repl_password: { get_attr: [mysql_repl_password, value] }
          server_debian_password: { get_attr: [mysql_debian_password, value] }
          remove_test_database: true
          remove_anonymous_users: true
          # root_network_acl: [ "10.%" ]
        # rax:
        #   mysql:
        #     innodb_buffer_pool_mempercent: 0.6
        run_list: [
          "recipe[apt]",
          "recipe[apt-periodic]",
          "recipe[build-essential]",
          "recipe[mysql::server]",
          "recipe[memcached]",
          "recipe[hollandbackup]",
          "recipe[hollandbackup::mysqldump]",
          "recipe[hollandbackup::main]",
          "recipe[hollandbackup::backupsets]",
          "recipe[hollandbackup::cron]"
        ]

outputs:
  private_key:
    value: { get_attr: [ssh_key, private_key] }

  mysql_root_password:
    value: { get_attr: [mysql_root_password, value] }

  database_networks:
     value: { get_attr: [database_server, networks] }
